### ISSUE TITLE
could you please provide a pretrained model link

### ISSUE THREAD

**Issue by boy-be-ambitious** [jainammm/TableNet#12]
hi, could you please provide a trained model on this big dataset, so we can directly use it on our new pdf.

**Comment by murtuzamdahod** [comment]
+1

**Comment by martian1231** [comment]
+1

**Comment by teng-pixiumdigital** [comment]
@murtuzamdahod  @realize-qzq 
I found a Table-Net implementation on another github provide with Pre-trained model.
Search tomassosorio/OCR_tablenet on google

**Comment by boy-be-ambitious** [comment]
> @murtuzamdahod @realize-qzq
> I found a Table-Net implementation on another github provide with Pre-trained model.
> Search tomassosorio/OCR_tablenet on google

Thanks for your help!
