### ISSUE TITLE
/content/drive/MyDrive/Marmot/Marmot_data/10.1.1.33.5766_4.jpg; No such file or directory

### ISSUE THREAD

**Issue by QWERDFBAS** [jainammm/TableNet#7]

**Comment by QWERDFBAS** [comment]
What is the internal structure of the data set?

**Comment by jainammm** [comment]
You'd have to download the dataset from the link given in the paper.

**Comment by thanhnc1308** [comment]
I got this issue too. Do I have to convert the bmp into jpg in Marmot_data folder?

**Comment by jainammm** [comment]
Please have a look at the data_proprocess folder @thanhnc1308

**Comment by murtuzamdahod** [comment]
Hello @jainammm ,
The dataset is in bmp format by default. The dataset folder only deals with column mask and table mask . Also when i read the dataset in jupyter notebook, it gives ms 4 dimensions.

**Comment by meet1919** [comment]
hey @jainammm the data_preprocess generates images of column and table mask. This code successfully works for me. But when I run the notebook I get the above error. i think this line doesn't work `file_path = tf.strings.regex_replace(file_path, '.xml', '.jpg')` which throws error later `NotFoundError: NewRandomAccessFile failed to Create/Open: dataset\Marmot_data\10.1.1.160.590_45.jpg : The system cannot find the file specified.`

**Comment by jainammm** [comment]
@meet1919 please check if the path provided is correct

**Comment by meet1919** [comment]
path was correct but I changed all the .bmp file to .jpg file and the code work perfectly

**Comment by lhm11111** [comment]
> 路径是正确的，但我将所有 .bmp 文件更改为 .jpg 文件并且代码运行良好

请问可以理解为你输入的为一个jpg格式而不是xml格式的么？
